#name boy
boy_names = [ "hasan" , "kalam" , "mamad" , "hossein" , "amir" , "abolfazl" , "gholam" , "sami" , "mohammad" , "reza" , "mehdi"]
print (boy_names [+1])
print (boy_names [+2])
print (boy_names [+3])
print (boy_names [-1])
print (boy_names [-2])
print (boy_names [-3])
print (len(boy_names))
boy_names.append ("hamid")
print (boy_names)
boy_names.remove ("reza")
print (boy_names)
boy_names.extend("abolfazl")
print (game_list)
boy_names.insert(3 , "sadegh")
print (boy_names)
boy_names.pop(2)
print(boy_names)
#game
game_list = [" forza" , "gta" , "cod" , "tlou" , "hitman " , "blackops" , "grandtheftv" , "fortnite" ] 
print (game_list [+1])
print (game_list [+2])
print (game_list [+3])
print (game_list [-1])
print (game_list [-2])
print (game_list [-3])
print (len(game_list))
game_list.append("player unknow battle grounds")
print (game_list)
game_list.remove ("fortnite")
print (game_list)
game_list.remove("evil")
print (game_list)
game_list.extend("hitman")
print (game_list)
game_list.insert(3 , "call of duty")
print (game_list)
game_list.pop(2)
print (game_list)
# Girl name
girls_name = [ "nastaran" , "fahime" , "zeynab" , "zohre" , "mina" , "mobina" , "somaye" , "reyhane"]
print (len(girls_name))
print (girls_name [2])
print (girls_name [3])
print (girls_name [0])
print (girls_name [-2])
print (girls_name [-3])
print (girls_name [-5])
print(len(girls_name))
girls_name.append (" bahare ")
print (girls_name)
girls_name.remove("sozane")
print(girls_name)
girls_name.extend ("niki")
print (girls_name)
girls_name.insert (2 , "nazanin")
print (girls_name)
girls_name.pop (5)
print(girls_name)
#city
city = [ "amol" , "babol" , "ghaemshahr" , "shiraz" , "sari" , "joybar" , "iranshahr"]
print (city[1])
print (city[2])
print (city[0])
print (city[-1])
print (city[-2])
print (city[-3])
print (len(city))
city.append ("kerman")
print (city)
city.remove ("semnan")
print (city)
city.extend ("matankola")
print (city)
city.insert (2 , "shirgah")
print (city)
city.pop ( 5 )
print (city)
#goshi
goshi = [ "13 promax" , "14 promaxi" ,  "11 promax" , "15 promax" , "13 pro" , "12 pro" , "11 pro" , "14 pro" , "x pro" , "xs pro"]
print (len(goshi))
print(goshi [1])
print (goshi [2])
print(goshi [3])
print(goshi [-1])
print(goshi [-5])
print(goshi [-6])
goshi.append ("13 promax")
print (goshi)
goshi.remove ("12 promax")
print (goshi)
goshi.extend ("11 promax")
print(goshi)
goshi.insert (2 , "15 promax")
print (goshi)
goshi.pop (4)
print (goshi)
